adding sshca config
screwdriver-cd/buildcluster-queue-worker pull request #126
Opened 2021-07-20 15:30 UTC by mchengat

## Context

adding sshca secret

## Objective

adding sshca secret

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-07-22 18:47 UTC, pritamstyz4ever requested changes

2021-07-22 18:47 UTC, pritamstyz4ever commented on config/custom-environment-variables.yaml
> +            secrets:
I understand, this means a custom user secret defined as k8s secret in JSON. Probably renaming it to userSecrets will avoid confusion.

2021-07-23 17:47 UTC, pritamstyz4ever approved these changes

2021-07-26 17:44 UTC, jithine commented on config/custom-environment-variables.yaml
> +            # add sshca key
update it to say `# secrets to be exposed inside build container as environment variables`

2021-07-26 17:45 UTC, jithine commented on config/custom-environment-variables.yaml
> +            userSecrets:
perhaps call it `buildSecrerts` ? so that context is clear

2021-07-26 18:34 UTC, jithine approved these changes

2021-07-26 19:48 UTC, merged